spring.application.name=demo.websocket
server.port=4000

spring.data.mongodb.uri=mongodb://localhost:27017/demochat

app.cors.allowed-origins=http://localhost:3000

# Logging configuration
logging.level.root=INFO
logging.level.com.example.demo.websocket=DEBUG
logging.file.name=logs/application.log
